using PassKeep.Lib.Contracts.KeePass;

namespace PassKeep.Lib.KeePass.Rng
{
    /// <summary>
    /// Represents a random number generation algorithm
    /// used by KeePas to protect data in memory.
    /// </summary>
    /// <remarks>The random numbers generated by subclasses
    /// of AbstractRng are used to encrypt "protected strings"
    /// in the plaintext of the KeePass XML tree.</remarks>
    public abstract class AbstractRng : IRandomNumberGenerator
    {
        protected internal byte[] Seed { get; set; }

        public AbstractRng(byte[] seed)
        {
            Seed = seed;
        }

        public abstract byte[] GetBytes(uint numBytes);
        public abstract IRandomNumberGenerator Clone();
        public abstract RngAlgorithm Algorithm { get; }
    }
}
