//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace KeepItSafe.KeePassLib {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class KeePassFile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private KeePassFileMeta metaField;
        
        private KeePassFileRoot rootField;
        
        /// <remarks/>
        public KeePassFileMeta Meta {
            get {
                return this.metaField;
            }
            set {
                this.metaField = value;
                this.RaisePropertyChanged("Meta");
            }
        }
        
        /// <remarks/>
        public KeePassFileRoot Root {
            get {
                return this.rootField;
            }
            set {
                this.rootField = value;
                this.RaisePropertyChanged("Root");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileMeta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string generatorField;
        
        private object databaseNameField;
        
        private System.DateTime databaseNameChangedField;
        
        private object databaseDescriptionField;
        
        private System.DateTime databaseDescriptionChangedField;
        
        private object defaultUserNameField;
        
        private System.DateTime defaultUserNameChangedField;
        
        private ushort maintenanceHistoryDaysField;
        
        private object colorField;
        
        private System.DateTime masterKeyChangedField;
        
        private sbyte masterKeyChangeRecField;
        
        private sbyte masterKeyChangeForceField;
        
        private KeePassFileMetaMemoryProtection memoryProtectionField;
        
        private string recycleBinEnabledField;
        
        private string recycleBinUUIDField;
        
        private System.DateTime recycleBinChangedField;
        
        private string entryTemplatesGroupField;
        
        private System.DateTime entryTemplatesGroupChangedField;
        
        private byte historyMaxItemsField;
        
        private uint historyMaxSizeField;
        
        private string lastSelectedGroupField;
        
        private string lastTopVisibleGroupField;
        
        private object binariesField;
        
        private object customDataField;
        
        /// <remarks/>
        public string Generator {
            get {
                return this.generatorField;
            }
            set {
                this.generatorField = value;
                this.RaisePropertyChanged("Generator");
            }
        }
        
        /// <remarks/>
        public object DatabaseName {
            get {
                return this.databaseNameField;
            }
            set {
                this.databaseNameField = value;
                this.RaisePropertyChanged("DatabaseName");
            }
        }
        
        /// <remarks/>
        public System.DateTime DatabaseNameChanged {
            get {
                return this.databaseNameChangedField;
            }
            set {
                this.databaseNameChangedField = value;
                this.RaisePropertyChanged("DatabaseNameChanged");
            }
        }
        
        /// <remarks/>
        public object DatabaseDescription {
            get {
                return this.databaseDescriptionField;
            }
            set {
                this.databaseDescriptionField = value;
                this.RaisePropertyChanged("DatabaseDescription");
            }
        }
        
        /// <remarks/>
        public System.DateTime DatabaseDescriptionChanged {
            get {
                return this.databaseDescriptionChangedField;
            }
            set {
                this.databaseDescriptionChangedField = value;
                this.RaisePropertyChanged("DatabaseDescriptionChanged");
            }
        }
        
        /// <remarks/>
        public object DefaultUserName {
            get {
                return this.defaultUserNameField;
            }
            set {
                this.defaultUserNameField = value;
                this.RaisePropertyChanged("DefaultUserName");
            }
        }
        
        /// <remarks/>
        public System.DateTime DefaultUserNameChanged {
            get {
                return this.defaultUserNameChangedField;
            }
            set {
                this.defaultUserNameChangedField = value;
                this.RaisePropertyChanged("DefaultUserNameChanged");
            }
        }
        
        /// <remarks/>
        public ushort MaintenanceHistoryDays {
            get {
                return this.maintenanceHistoryDaysField;
            }
            set {
                this.maintenanceHistoryDaysField = value;
                this.RaisePropertyChanged("MaintenanceHistoryDays");
            }
        }
        
        /// <remarks/>
        public object Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
                this.RaisePropertyChanged("Color");
            }
        }
        
        /// <remarks/>
        public System.DateTime MasterKeyChanged {
            get {
                return this.masterKeyChangedField;
            }
            set {
                this.masterKeyChangedField = value;
                this.RaisePropertyChanged("MasterKeyChanged");
            }
        }
        
        /// <remarks/>
        public sbyte MasterKeyChangeRec {
            get {
                return this.masterKeyChangeRecField;
            }
            set {
                this.masterKeyChangeRecField = value;
                this.RaisePropertyChanged("MasterKeyChangeRec");
            }
        }
        
        /// <remarks/>
        public sbyte MasterKeyChangeForce {
            get {
                return this.masterKeyChangeForceField;
            }
            set {
                this.masterKeyChangeForceField = value;
                this.RaisePropertyChanged("MasterKeyChangeForce");
            }
        }
        
        /// <remarks/>
        public KeePassFileMetaMemoryProtection MemoryProtection {
            get {
                return this.memoryProtectionField;
            }
            set {
                this.memoryProtectionField = value;
                this.RaisePropertyChanged("MemoryProtection");
            }
        }
        
        /// <remarks/>
        public string RecycleBinEnabled {
            get {
                return this.recycleBinEnabledField;
            }
            set {
                this.recycleBinEnabledField = value;
                this.RaisePropertyChanged("RecycleBinEnabled");
            }
        }
        
        /// <remarks/>
        public string RecycleBinUUID {
            get {
                return this.recycleBinUUIDField;
            }
            set {
                this.recycleBinUUIDField = value;
                this.RaisePropertyChanged("RecycleBinUUID");
            }
        }
        
        /// <remarks/>
        public System.DateTime RecycleBinChanged {
            get {
                return this.recycleBinChangedField;
            }
            set {
                this.recycleBinChangedField = value;
                this.RaisePropertyChanged("RecycleBinChanged");
            }
        }
        
        /// <remarks/>
        public string EntryTemplatesGroup {
            get {
                return this.entryTemplatesGroupField;
            }
            set {
                this.entryTemplatesGroupField = value;
                this.RaisePropertyChanged("EntryTemplatesGroup");
            }
        }
        
        /// <remarks/>
        public System.DateTime EntryTemplatesGroupChanged {
            get {
                return this.entryTemplatesGroupChangedField;
            }
            set {
                this.entryTemplatesGroupChangedField = value;
                this.RaisePropertyChanged("EntryTemplatesGroupChanged");
            }
        }
        
        /// <remarks/>
        public byte HistoryMaxItems {
            get {
                return this.historyMaxItemsField;
            }
            set {
                this.historyMaxItemsField = value;
                this.RaisePropertyChanged("HistoryMaxItems");
            }
        }
        
        /// <remarks/>
        public uint HistoryMaxSize {
            get {
                return this.historyMaxSizeField;
            }
            set {
                this.historyMaxSizeField = value;
                this.RaisePropertyChanged("HistoryMaxSize");
            }
        }
        
        /// <remarks/>
        public string LastSelectedGroup {
            get {
                return this.lastSelectedGroupField;
            }
            set {
                this.lastSelectedGroupField = value;
                this.RaisePropertyChanged("LastSelectedGroup");
            }
        }
        
        /// <remarks/>
        public string LastTopVisibleGroup {
            get {
                return this.lastTopVisibleGroupField;
            }
            set {
                this.lastTopVisibleGroupField = value;
                this.RaisePropertyChanged("LastTopVisibleGroup");
            }
        }
        
        /// <remarks/>
        public object Binaries {
            get {
                return this.binariesField;
            }
            set {
                this.binariesField = value;
                this.RaisePropertyChanged("Binaries");
            }
        }
        
        /// <remarks/>
        public object CustomData {
            get {
                return this.customDataField;
            }
            set {
                this.customDataField = value;
                this.RaisePropertyChanged("CustomData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileMetaMemoryProtection : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string protectTitleField;
        
        private string protectUserNameField;
        
        private string protectPasswordField;
        
        private string protectURLField;
        
        private string protectNotesField;
        
        /// <remarks/>
        public string ProtectTitle {
            get {
                return this.protectTitleField;
            }
            set {
                this.protectTitleField = value;
                this.RaisePropertyChanged("ProtectTitle");
            }
        }
        
        /// <remarks/>
        public string ProtectUserName {
            get {
                return this.protectUserNameField;
            }
            set {
                this.protectUserNameField = value;
                this.RaisePropertyChanged("ProtectUserName");
            }
        }
        
        /// <remarks/>
        public string ProtectPassword {
            get {
                return this.protectPasswordField;
            }
            set {
                this.protectPasswordField = value;
                this.RaisePropertyChanged("ProtectPassword");
            }
        }
        
        /// <remarks/>
        public string ProtectURL {
            get {
                return this.protectURLField;
            }
            set {
                this.protectURLField = value;
                this.RaisePropertyChanged("ProtectURL");
            }
        }
        
        /// <remarks/>
        public string ProtectNotes {
            get {
                return this.protectNotesField;
            }
            set {
                this.protectNotesField = value;
                this.RaisePropertyChanged("ProtectNotes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileRoot : object, System.ComponentModel.INotifyPropertyChanged {
        
        private KeePassFileRootGroup groupField;
        
        private KeePassFileRootDeletedObject[] deletedObjectsField;
        
        /// <remarks/>
        public KeePassFileRootGroup Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
                this.RaisePropertyChanged("Group");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DeletedObject", IsNullable=false)]
        public KeePassFileRootDeletedObject[] DeletedObjects {
            get {
                return this.deletedObjectsField;
            }
            set {
                this.deletedObjectsField = value;
                this.RaisePropertyChanged("DeletedObjects");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileRootGroup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uUIDField;
        
        private string nameField;
        
        private object notesField;
        
        private byte iconIDField;
        
        private KeePassFileRootGroupTimes timesField;
        
        private string isExpandedField;
        
        private object defaultAutoTypeSequenceField;
        
        private string enableAutoTypeField;
        
        private string enableSearchingField;
        
        private string lastTopVisibleEntryField;
        
        private KeePassFileRootGroupGroup[] groupField;
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        public object Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("Notes");
            }
        }
        
        /// <remarks/>
        public byte IconID {
            get {
                return this.iconIDField;
            }
            set {
                this.iconIDField = value;
                this.RaisePropertyChanged("IconID");
            }
        }
        
        /// <remarks/>
        public KeePassFileRootGroupTimes Times {
            get {
                return this.timesField;
            }
            set {
                this.timesField = value;
                this.RaisePropertyChanged("Times");
            }
        }
        
        /// <remarks/>
        public string IsExpanded {
            get {
                return this.isExpandedField;
            }
            set {
                this.isExpandedField = value;
                this.RaisePropertyChanged("IsExpanded");
            }
        }
        
        /// <remarks/>
        public object DefaultAutoTypeSequence {
            get {
                return this.defaultAutoTypeSequenceField;
            }
            set {
                this.defaultAutoTypeSequenceField = value;
                this.RaisePropertyChanged("DefaultAutoTypeSequence");
            }
        }
        
        /// <remarks/>
        public string EnableAutoType {
            get {
                return this.enableAutoTypeField;
            }
            set {
                this.enableAutoTypeField = value;
                this.RaisePropertyChanged("EnableAutoType");
            }
        }
        
        /// <remarks/>
        public string EnableSearching {
            get {
                return this.enableSearchingField;
            }
            set {
                this.enableSearchingField = value;
                this.RaisePropertyChanged("EnableSearching");
            }
        }
        
        /// <remarks/>
        public string LastTopVisibleEntry {
            get {
                return this.lastTopVisibleEntryField;
            }
            set {
                this.lastTopVisibleEntryField = value;
                this.RaisePropertyChanged("LastTopVisibleEntry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Group")]
        public KeePassFileRootGroupGroup[] Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
                this.RaisePropertyChanged("Group");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileRootGroupTimes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime lastModificationTimeField;
        
        private System.DateTime creationTimeField;
        
        private System.DateTime lastAccessTimeField;
        
        private System.DateTime expiryTimeField;
        
        private string expiresField;
        
        private ushort usageCountField;
        
        private System.DateTime locationChangedField;
        
        /// <remarks/>
        public System.DateTime LastModificationTime {
            get {
                return this.lastModificationTimeField;
            }
            set {
                this.lastModificationTimeField = value;
                this.RaisePropertyChanged("LastModificationTime");
            }
        }
        
        /// <remarks/>
        public System.DateTime CreationTime {
            get {
                return this.creationTimeField;
            }
            set {
                this.creationTimeField = value;
                this.RaisePropertyChanged("CreationTime");
            }
        }
        
        /// <remarks/>
        public System.DateTime LastAccessTime {
            get {
                return this.lastAccessTimeField;
            }
            set {
                this.lastAccessTimeField = value;
                this.RaisePropertyChanged("LastAccessTime");
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpiryTime {
            get {
                return this.expiryTimeField;
            }
            set {
                this.expiryTimeField = value;
                this.RaisePropertyChanged("ExpiryTime");
            }
        }
        
        /// <remarks/>
        public string Expires {
            get {
                return this.expiresField;
            }
            set {
                this.expiresField = value;
                this.RaisePropertyChanged("Expires");
            }
        }
        
        /// <remarks/>
        public ushort UsageCount {
            get {
                return this.usageCountField;
            }
            set {
                this.usageCountField = value;
                this.RaisePropertyChanged("UsageCount");
            }
        }
        
        /// <remarks/>
        public System.DateTime LocationChanged {
            get {
                return this.locationChangedField;
            }
            set {
                this.locationChangedField = value;
                this.RaisePropertyChanged("LocationChanged");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileRootGroupGroup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uUIDField;
        
        private string nameField;
        
        private object notesField;
        
        private byte iconIDField;
        
        private KeePassFileRootGroupGroupTimes timesField;
        
        private string isExpandedField;
        
        private object defaultAutoTypeSequenceField;
        
        private string enableAutoTypeField;
        
        private string enableSearchingField;
        
        private string lastTopVisibleEntryField;
        
        private KeePassFileRootGroupGroupEntry[] entryField;
        
        private KeePassFileRootGroupGroupGroup[] groupField;
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        public object Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("Notes");
            }
        }
        
        /// <remarks/>
        public byte IconID {
            get {
                return this.iconIDField;
            }
            set {
                this.iconIDField = value;
                this.RaisePropertyChanged("IconID");
            }
        }
        
        /// <remarks/>
        public KeePassFileRootGroupGroupTimes Times {
            get {
                return this.timesField;
            }
            set {
                this.timesField = value;
                this.RaisePropertyChanged("Times");
            }
        }
        
        /// <remarks/>
        public string IsExpanded {
            get {
                return this.isExpandedField;
            }
            set {
                this.isExpandedField = value;
                this.RaisePropertyChanged("IsExpanded");
            }
        }
        
        /// <remarks/>
        public object DefaultAutoTypeSequence {
            get {
                return this.defaultAutoTypeSequenceField;
            }
            set {
                this.defaultAutoTypeSequenceField = value;
                this.RaisePropertyChanged("DefaultAutoTypeSequence");
            }
        }
        
        /// <remarks/>
        public string EnableAutoType {
            get {
                return this.enableAutoTypeField;
            }
            set {
                this.enableAutoTypeField = value;
                this.RaisePropertyChanged("EnableAutoType");
            }
        }
        
        /// <remarks/>
        public string EnableSearching {
            get {
                return this.enableSearchingField;
            }
            set {
                this.enableSearchingField = value;
                this.RaisePropertyChanged("EnableSearching");
            }
        }
        
        /// <remarks/>
        public string LastTopVisibleEntry {
            get {
                return this.lastTopVisibleEntryField;
            }
            set {
                this.lastTopVisibleEntryField = value;
                this.RaisePropertyChanged("LastTopVisibleEntry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Entry")]
        public KeePassFileRootGroupGroupEntry[] Entry {
            get {
                return this.entryField;
            }
            set {
                this.entryField = value;
                this.RaisePropertyChanged("Entry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Group")]
        public KeePassFileRootGroupGroupGroup[] Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
                this.RaisePropertyChanged("Group");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileRootGroupGroupTimes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime lastModificationTimeField;
        
        private System.DateTime creationTimeField;
        
        private System.DateTime lastAccessTimeField;
        
        private System.DateTime expiryTimeField;
        
        private string expiresField;
        
        private ushort usageCountField;
        
        private System.DateTime locationChangedField;
        
        /// <remarks/>
        public System.DateTime LastModificationTime {
            get {
                return this.lastModificationTimeField;
            }
            set {
                this.lastModificationTimeField = value;
                this.RaisePropertyChanged("LastModificationTime");
            }
        }
        
        /// <remarks/>
        public System.DateTime CreationTime {
            get {
                return this.creationTimeField;
            }
            set {
                this.creationTimeField = value;
                this.RaisePropertyChanged("CreationTime");
            }
        }
        
        /// <remarks/>
        public System.DateTime LastAccessTime {
            get {
                return this.lastAccessTimeField;
            }
            set {
                this.lastAccessTimeField = value;
                this.RaisePropertyChanged("LastAccessTime");
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpiryTime {
            get {
                return this.expiryTimeField;
            }
            set {
                this.expiryTimeField = value;
                this.RaisePropertyChanged("ExpiryTime");
            }
        }
        
        /// <remarks/>
        public string Expires {
            get {
                return this.expiresField;
            }
            set {
                this.expiresField = value;
                this.RaisePropertyChanged("Expires");
            }
        }
        
        /// <remarks/>
        public ushort UsageCount {
            get {
                return this.usageCountField;
            }
            set {
                this.usageCountField = value;
                this.RaisePropertyChanged("UsageCount");
            }
        }
        
        /// <remarks/>
        public System.DateTime LocationChanged {
            get {
                return this.locationChangedField;
            }
            set {
                this.locationChangedField = value;
                this.RaisePropertyChanged("LocationChanged");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileRootGroupGroupEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uUIDField;
        
        private byte iconIDField;
        
        private object foregroundColorField;
        
        private object backgroundColorField;
        
        private object overrideURLField;
        
        private object tagsField;
        
        private KeePassFileRootGroupGroupEntryTimes timesField;
        
        private KeePassFileRootGroupGroupEntryString[] stringField;
        
        private KeePassFileRootGroupGroupEntryAutoType autoTypeField;
        
        private KeePassFileRootGroupGroupEntryEntry[] historyField;
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        public byte IconID {
            get {
                return this.iconIDField;
            }
            set {
                this.iconIDField = value;
                this.RaisePropertyChanged("IconID");
            }
        }
        
        /// <remarks/>
        public object ForegroundColor {
            get {
                return this.foregroundColorField;
            }
            set {
                this.foregroundColorField = value;
                this.RaisePropertyChanged("ForegroundColor");
            }
        }
        
        /// <remarks/>
        public object BackgroundColor {
            get {
                return this.backgroundColorField;
            }
            set {
                this.backgroundColorField = value;
                this.RaisePropertyChanged("BackgroundColor");
            }
        }
        
        /// <remarks/>
        public object OverrideURL {
            get {
                return this.overrideURLField;
            }
            set {
                this.overrideURLField = value;
                this.RaisePropertyChanged("OverrideURL");
            }
        }
        
        /// <remarks/>
        public object Tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
                this.RaisePropertyChanged("Tags");
            }
        }
        
        /// <remarks/>
        public KeePassFileRootGroupGroupEntryTimes Times {
            get {
                return this.timesField;
            }
            set {
                this.timesField = value;
                this.RaisePropertyChanged("Times");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("String")]
        public KeePassFileRootGroupGroupEntryString[] String {
            get {
                return this.stringField;
            }
            set {
                this.stringField = value;
                this.RaisePropertyChanged("String");
            }
        }
        
        /// <remarks/>
        public KeePassFileRootGroupGroupEntryAutoType AutoType {
            get {
                return this.autoTypeField;
            }
            set {
                this.autoTypeField = value;
                this.RaisePropertyChanged("AutoType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Entry", IsNullable=false)]
        public KeePassFileRootGroupGroupEntryEntry[] History {
            get {
                return this.historyField;
            }
            set {
                this.historyField = value;
                this.RaisePropertyChanged("History");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileRootGroupGroupEntryTimes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime lastModificationTimeField;
        
        private System.DateTime creationTimeField;
        
        private System.DateTime lastAccessTimeField;
        
        private System.DateTime expiryTimeField;
        
        private string expiresField;
        
        private byte usageCountField;
        
        private System.DateTime locationChangedField;
        
        /// <remarks/>
        public System.DateTime LastModificationTime {
            get {
                return this.lastModificationTimeField;
            }
            set {
                this.lastModificationTimeField = value;
                this.RaisePropertyChanged("LastModificationTime");
            }
        }
        
        /// <remarks/>
        public System.DateTime CreationTime {
            get {
                return this.creationTimeField;
            }
            set {
                this.creationTimeField = value;
                this.RaisePropertyChanged("CreationTime");
            }
        }
        
        /// <remarks/>
        public System.DateTime LastAccessTime {
            get {
                return this.lastAccessTimeField;
            }
            set {
                this.lastAccessTimeField = value;
                this.RaisePropertyChanged("LastAccessTime");
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpiryTime {
            get {
                return this.expiryTimeField;
            }
            set {
                this.expiryTimeField = value;
                this.RaisePropertyChanged("ExpiryTime");
            }
        }
        
        /// <remarks/>
        public string Expires {
            get {
                return this.expiresField;
            }
            set {
                this.expiresField = value;
                this.RaisePropertyChanged("Expires");
            }
        }
        
        /// <remarks/>
        public byte UsageCount {
            get {
                return this.usageCountField;
            }
            set {
                this.usageCountField = value;
                this.RaisePropertyChanged("UsageCount");
            }
        }
        
        /// <remarks/>
        public System.DateTime LocationChanged {
            get {
                return this.locationChangedField;
            }
            set {
                this.locationChangedField = value;
                this.RaisePropertyChanged("LocationChanged");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileRootGroupGroupEntryString : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private KeePassFileRootGroupGroupEntryStringValue valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        public KeePassFileRootGroupGroupEntryStringValue Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileRootGroupGroupEntryStringValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string protectedField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Protected {
            get {
                return this.protectedField;
            }
            set {
                this.protectedField = value;
                this.RaisePropertyChanged("Protected");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileRootGroupGroupEntryAutoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string enabledField;
        
        private byte dataTransferObfuscationField;
        
        private KeePassFileRootGroupGroupEntryAutoTypeAssociation associationField;
        
        /// <remarks/>
        public string Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
                this.RaisePropertyChanged("Enabled");
            }
        }
        
        /// <remarks/>
        public byte DataTransferObfuscation {
            get {
                return this.dataTransferObfuscationField;
            }
            set {
                this.dataTransferObfuscationField = value;
                this.RaisePropertyChanged("DataTransferObfuscation");
            }
        }
        
        /// <remarks/>
        public KeePassFileRootGroupGroupEntryAutoTypeAssociation Association {
            get {
                return this.associationField;
            }
            set {
                this.associationField = value;
                this.RaisePropertyChanged("Association");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileRootGroupGroupEntryAutoTypeAssociation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string windowField;
        
        private string keystrokeSequenceField;
        
        /// <remarks/>
        public string Window {
            get {
                return this.windowField;
            }
            set {
                this.windowField = value;
                this.RaisePropertyChanged("Window");
            }
        }
        
        /// <remarks/>
        public string KeystrokeSequence {
            get {
                return this.keystrokeSequenceField;
            }
            set {
                this.keystrokeSequenceField = value;
                this.RaisePropertyChanged("KeystrokeSequence");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileRootGroupGroupEntryEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uUIDField;
        
        private byte iconIDField;
        
        private object foregroundColorField;
        
        private object backgroundColorField;
        
        private object overrideURLField;
        
        private object tagsField;
        
        private KeePassFileRootGroupGroupEntryEntryTimes timesField;
        
        private KeePassFileRootGroupGroupEntryEntryString[] stringField;
        
        private KeePassFileRootGroupGroupEntryEntryAutoType autoTypeField;
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        public byte IconID {
            get {
                return this.iconIDField;
            }
            set {
                this.iconIDField = value;
                this.RaisePropertyChanged("IconID");
            }
        }
        
        /// <remarks/>
        public object ForegroundColor {
            get {
                return this.foregroundColorField;
            }
            set {
                this.foregroundColorField = value;
                this.RaisePropertyChanged("ForegroundColor");
            }
        }
        
        /// <remarks/>
        public object BackgroundColor {
            get {
                return this.backgroundColorField;
            }
            set {
                this.backgroundColorField = value;
                this.RaisePropertyChanged("BackgroundColor");
            }
        }
        
        /// <remarks/>
        public object OverrideURL {
            get {
                return this.overrideURLField;
            }
            set {
                this.overrideURLField = value;
                this.RaisePropertyChanged("OverrideURL");
            }
        }
        
        /// <remarks/>
        public object Tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
                this.RaisePropertyChanged("Tags");
            }
        }
        
        /// <remarks/>
        public KeePassFileRootGroupGroupEntryEntryTimes Times {
            get {
                return this.timesField;
            }
            set {
                this.timesField = value;
                this.RaisePropertyChanged("Times");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("String")]
        public KeePassFileRootGroupGroupEntryEntryString[] String {
            get {
                return this.stringField;
            }
            set {
                this.stringField = value;
                this.RaisePropertyChanged("String");
            }
        }
        
        /// <remarks/>
        public KeePassFileRootGroupGroupEntryEntryAutoType AutoType {
            get {
                return this.autoTypeField;
            }
            set {
                this.autoTypeField = value;
                this.RaisePropertyChanged("AutoType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileRootGroupGroupEntryEntryTimes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime lastModificationTimeField;
        
        private System.DateTime creationTimeField;
        
        private System.DateTime lastAccessTimeField;
        
        private System.DateTime expiryTimeField;
        
        private string expiresField;
        
        private byte usageCountField;
        
        private System.DateTime locationChangedField;
        
        /// <remarks/>
        public System.DateTime LastModificationTime {
            get {
                return this.lastModificationTimeField;
            }
            set {
                this.lastModificationTimeField = value;
                this.RaisePropertyChanged("LastModificationTime");
            }
        }
        
        /// <remarks/>
        public System.DateTime CreationTime {
            get {
                return this.creationTimeField;
            }
            set {
                this.creationTimeField = value;
                this.RaisePropertyChanged("CreationTime");
            }
        }
        
        /// <remarks/>
        public System.DateTime LastAccessTime {
            get {
                return this.lastAccessTimeField;
            }
            set {
                this.lastAccessTimeField = value;
                this.RaisePropertyChanged("LastAccessTime");
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpiryTime {
            get {
                return this.expiryTimeField;
            }
            set {
                this.expiryTimeField = value;
                this.RaisePropertyChanged("ExpiryTime");
            }
        }
        
        /// <remarks/>
        public string Expires {
            get {
                return this.expiresField;
            }
            set {
                this.expiresField = value;
                this.RaisePropertyChanged("Expires");
            }
        }
        
        /// <remarks/>
        public byte UsageCount {
            get {
                return this.usageCountField;
            }
            set {
                this.usageCountField = value;
                this.RaisePropertyChanged("UsageCount");
            }
        }
        
        /// <remarks/>
        public System.DateTime LocationChanged {
            get {
                return this.locationChangedField;
            }
            set {
                this.locationChangedField = value;
                this.RaisePropertyChanged("LocationChanged");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileRootGroupGroupEntryEntryString : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private KeePassFileRootGroupGroupEntryEntryStringValue valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        public KeePassFileRootGroupGroupEntryEntryStringValue Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileRootGroupGroupEntryEntryStringValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string protectedField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Protected {
            get {
                return this.protectedField;
            }
            set {
                this.protectedField = value;
                this.RaisePropertyChanged("Protected");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileRootGroupGroupEntryEntryAutoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string enabledField;
        
        private byte dataTransferObfuscationField;
        
        /// <remarks/>
        public string Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
                this.RaisePropertyChanged("Enabled");
            }
        }
        
        /// <remarks/>
        public byte DataTransferObfuscation {
            get {
                return this.dataTransferObfuscationField;
            }
            set {
                this.dataTransferObfuscationField = value;
                this.RaisePropertyChanged("DataTransferObfuscation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileRootGroupGroupGroup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uUIDField;
        
        private string nameField;
        
        private object notesField;
        
        private byte iconIDField;
        
        private KeePassFileRootGroupGroupGroupTimes timesField;
        
        private string isExpandedField;
        
        private object defaultAutoTypeSequenceField;
        
        private string enableAutoTypeField;
        
        private string enableSearchingField;
        
        private string lastTopVisibleEntryField;
        
        private KeePassFileRootGroupGroupGroupEntry[] entryField;
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        public object Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("Notes");
            }
        }
        
        /// <remarks/>
        public byte IconID {
            get {
                return this.iconIDField;
            }
            set {
                this.iconIDField = value;
                this.RaisePropertyChanged("IconID");
            }
        }
        
        /// <remarks/>
        public KeePassFileRootGroupGroupGroupTimes Times {
            get {
                return this.timesField;
            }
            set {
                this.timesField = value;
                this.RaisePropertyChanged("Times");
            }
        }
        
        /// <remarks/>
        public string IsExpanded {
            get {
                return this.isExpandedField;
            }
            set {
                this.isExpandedField = value;
                this.RaisePropertyChanged("IsExpanded");
            }
        }
        
        /// <remarks/>
        public object DefaultAutoTypeSequence {
            get {
                return this.defaultAutoTypeSequenceField;
            }
            set {
                this.defaultAutoTypeSequenceField = value;
                this.RaisePropertyChanged("DefaultAutoTypeSequence");
            }
        }
        
        /// <remarks/>
        public string EnableAutoType {
            get {
                return this.enableAutoTypeField;
            }
            set {
                this.enableAutoTypeField = value;
                this.RaisePropertyChanged("EnableAutoType");
            }
        }
        
        /// <remarks/>
        public string EnableSearching {
            get {
                return this.enableSearchingField;
            }
            set {
                this.enableSearchingField = value;
                this.RaisePropertyChanged("EnableSearching");
            }
        }
        
        /// <remarks/>
        public string LastTopVisibleEntry {
            get {
                return this.lastTopVisibleEntryField;
            }
            set {
                this.lastTopVisibleEntryField = value;
                this.RaisePropertyChanged("LastTopVisibleEntry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Entry")]
        public KeePassFileRootGroupGroupGroupEntry[] Entry {
            get {
                return this.entryField;
            }
            set {
                this.entryField = value;
                this.RaisePropertyChanged("Entry");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileRootGroupGroupGroupTimes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime lastModificationTimeField;
        
        private System.DateTime creationTimeField;
        
        private System.DateTime lastAccessTimeField;
        
        private System.DateTime expiryTimeField;
        
        private string expiresField;
        
        private byte usageCountField;
        
        private System.DateTime locationChangedField;
        
        /// <remarks/>
        public System.DateTime LastModificationTime {
            get {
                return this.lastModificationTimeField;
            }
            set {
                this.lastModificationTimeField = value;
                this.RaisePropertyChanged("LastModificationTime");
            }
        }
        
        /// <remarks/>
        public System.DateTime CreationTime {
            get {
                return this.creationTimeField;
            }
            set {
                this.creationTimeField = value;
                this.RaisePropertyChanged("CreationTime");
            }
        }
        
        /// <remarks/>
        public System.DateTime LastAccessTime {
            get {
                return this.lastAccessTimeField;
            }
            set {
                this.lastAccessTimeField = value;
                this.RaisePropertyChanged("LastAccessTime");
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpiryTime {
            get {
                return this.expiryTimeField;
            }
            set {
                this.expiryTimeField = value;
                this.RaisePropertyChanged("ExpiryTime");
            }
        }
        
        /// <remarks/>
        public string Expires {
            get {
                return this.expiresField;
            }
            set {
                this.expiresField = value;
                this.RaisePropertyChanged("Expires");
            }
        }
        
        /// <remarks/>
        public byte UsageCount {
            get {
                return this.usageCountField;
            }
            set {
                this.usageCountField = value;
                this.RaisePropertyChanged("UsageCount");
            }
        }
        
        /// <remarks/>
        public System.DateTime LocationChanged {
            get {
                return this.locationChangedField;
            }
            set {
                this.locationChangedField = value;
                this.RaisePropertyChanged("LocationChanged");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileRootGroupGroupGroupEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uUIDField;
        
        private byte iconIDField;
        
        private object foregroundColorField;
        
        private object backgroundColorField;
        
        private object overrideURLField;
        
        private object tagsField;
        
        private KeePassFileRootGroupGroupGroupEntryTimes timesField;
        
        private KeePassFileRootGroupGroupGroupEntryString[] stringField;
        
        private KeePassFileRootGroupGroupGroupEntryAutoType autoTypeField;
        
        private KeePassFileRootGroupGroupGroupEntryEntry[] historyField;
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        public byte IconID {
            get {
                return this.iconIDField;
            }
            set {
                this.iconIDField = value;
                this.RaisePropertyChanged("IconID");
            }
        }
        
        /// <remarks/>
        public object ForegroundColor {
            get {
                return this.foregroundColorField;
            }
            set {
                this.foregroundColorField = value;
                this.RaisePropertyChanged("ForegroundColor");
            }
        }
        
        /// <remarks/>
        public object BackgroundColor {
            get {
                return this.backgroundColorField;
            }
            set {
                this.backgroundColorField = value;
                this.RaisePropertyChanged("BackgroundColor");
            }
        }
        
        /// <remarks/>
        public object OverrideURL {
            get {
                return this.overrideURLField;
            }
            set {
                this.overrideURLField = value;
                this.RaisePropertyChanged("OverrideURL");
            }
        }
        
        /// <remarks/>
        public object Tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
                this.RaisePropertyChanged("Tags");
            }
        }
        
        /// <remarks/>
        public KeePassFileRootGroupGroupGroupEntryTimes Times {
            get {
                return this.timesField;
            }
            set {
                this.timesField = value;
                this.RaisePropertyChanged("Times");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("String")]
        public KeePassFileRootGroupGroupGroupEntryString[] String {
            get {
                return this.stringField;
            }
            set {
                this.stringField = value;
                this.RaisePropertyChanged("String");
            }
        }
        
        /// <remarks/>
        public KeePassFileRootGroupGroupGroupEntryAutoType AutoType {
            get {
                return this.autoTypeField;
            }
            set {
                this.autoTypeField = value;
                this.RaisePropertyChanged("AutoType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Entry", IsNullable=false)]
        public KeePassFileRootGroupGroupGroupEntryEntry[] History {
            get {
                return this.historyField;
            }
            set {
                this.historyField = value;
                this.RaisePropertyChanged("History");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileRootGroupGroupGroupEntryTimes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime lastModificationTimeField;
        
        private System.DateTime creationTimeField;
        
        private System.DateTime lastAccessTimeField;
        
        private System.DateTime expiryTimeField;
        
        private string expiresField;
        
        private byte usageCountField;
        
        private System.DateTime locationChangedField;
        
        /// <remarks/>
        public System.DateTime LastModificationTime {
            get {
                return this.lastModificationTimeField;
            }
            set {
                this.lastModificationTimeField = value;
                this.RaisePropertyChanged("LastModificationTime");
            }
        }
        
        /// <remarks/>
        public System.DateTime CreationTime {
            get {
                return this.creationTimeField;
            }
            set {
                this.creationTimeField = value;
                this.RaisePropertyChanged("CreationTime");
            }
        }
        
        /// <remarks/>
        public System.DateTime LastAccessTime {
            get {
                return this.lastAccessTimeField;
            }
            set {
                this.lastAccessTimeField = value;
                this.RaisePropertyChanged("LastAccessTime");
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpiryTime {
            get {
                return this.expiryTimeField;
            }
            set {
                this.expiryTimeField = value;
                this.RaisePropertyChanged("ExpiryTime");
            }
        }
        
        /// <remarks/>
        public string Expires {
            get {
                return this.expiresField;
            }
            set {
                this.expiresField = value;
                this.RaisePropertyChanged("Expires");
            }
        }
        
        /// <remarks/>
        public byte UsageCount {
            get {
                return this.usageCountField;
            }
            set {
                this.usageCountField = value;
                this.RaisePropertyChanged("UsageCount");
            }
        }
        
        /// <remarks/>
        public System.DateTime LocationChanged {
            get {
                return this.locationChangedField;
            }
            set {
                this.locationChangedField = value;
                this.RaisePropertyChanged("LocationChanged");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileRootGroupGroupGroupEntryString : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private KeePassFileRootGroupGroupGroupEntryStringValue valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        public KeePassFileRootGroupGroupGroupEntryStringValue Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileRootGroupGroupGroupEntryStringValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string protectedField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Protected {
            get {
                return this.protectedField;
            }
            set {
                this.protectedField = value;
                this.RaisePropertyChanged("Protected");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileRootGroupGroupGroupEntryAutoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string enabledField;
        
        private byte dataTransferObfuscationField;
        
        /// <remarks/>
        public string Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
                this.RaisePropertyChanged("Enabled");
            }
        }
        
        /// <remarks/>
        public byte DataTransferObfuscation {
            get {
                return this.dataTransferObfuscationField;
            }
            set {
                this.dataTransferObfuscationField = value;
                this.RaisePropertyChanged("DataTransferObfuscation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileRootGroupGroupGroupEntryEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uUIDField;
        
        private byte iconIDField;
        
        private object foregroundColorField;
        
        private object backgroundColorField;
        
        private object overrideURLField;
        
        private object tagsField;
        
        private KeePassFileRootGroupGroupGroupEntryEntryTimes timesField;
        
        private KeePassFileRootGroupGroupGroupEntryEntryString[] stringField;
        
        private KeePassFileRootGroupGroupGroupEntryEntryAutoType autoTypeField;
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        public byte IconID {
            get {
                return this.iconIDField;
            }
            set {
                this.iconIDField = value;
                this.RaisePropertyChanged("IconID");
            }
        }
        
        /// <remarks/>
        public object ForegroundColor {
            get {
                return this.foregroundColorField;
            }
            set {
                this.foregroundColorField = value;
                this.RaisePropertyChanged("ForegroundColor");
            }
        }
        
        /// <remarks/>
        public object BackgroundColor {
            get {
                return this.backgroundColorField;
            }
            set {
                this.backgroundColorField = value;
                this.RaisePropertyChanged("BackgroundColor");
            }
        }
        
        /// <remarks/>
        public object OverrideURL {
            get {
                return this.overrideURLField;
            }
            set {
                this.overrideURLField = value;
                this.RaisePropertyChanged("OverrideURL");
            }
        }
        
        /// <remarks/>
        public object Tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
                this.RaisePropertyChanged("Tags");
            }
        }
        
        /// <remarks/>
        public KeePassFileRootGroupGroupGroupEntryEntryTimes Times {
            get {
                return this.timesField;
            }
            set {
                this.timesField = value;
                this.RaisePropertyChanged("Times");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("String")]
        public KeePassFileRootGroupGroupGroupEntryEntryString[] String {
            get {
                return this.stringField;
            }
            set {
                this.stringField = value;
                this.RaisePropertyChanged("String");
            }
        }
        
        /// <remarks/>
        public KeePassFileRootGroupGroupGroupEntryEntryAutoType AutoType {
            get {
                return this.autoTypeField;
            }
            set {
                this.autoTypeField = value;
                this.RaisePropertyChanged("AutoType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileRootGroupGroupGroupEntryEntryTimes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime lastModificationTimeField;
        
        private System.DateTime creationTimeField;
        
        private System.DateTime lastAccessTimeField;
        
        private System.DateTime expiryTimeField;
        
        private string expiresField;
        
        private byte usageCountField;
        
        private System.DateTime locationChangedField;
        
        /// <remarks/>
        public System.DateTime LastModificationTime {
            get {
                return this.lastModificationTimeField;
            }
            set {
                this.lastModificationTimeField = value;
                this.RaisePropertyChanged("LastModificationTime");
            }
        }
        
        /// <remarks/>
        public System.DateTime CreationTime {
            get {
                return this.creationTimeField;
            }
            set {
                this.creationTimeField = value;
                this.RaisePropertyChanged("CreationTime");
            }
        }
        
        /// <remarks/>
        public System.DateTime LastAccessTime {
            get {
                return this.lastAccessTimeField;
            }
            set {
                this.lastAccessTimeField = value;
                this.RaisePropertyChanged("LastAccessTime");
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpiryTime {
            get {
                return this.expiryTimeField;
            }
            set {
                this.expiryTimeField = value;
                this.RaisePropertyChanged("ExpiryTime");
            }
        }
        
        /// <remarks/>
        public string Expires {
            get {
                return this.expiresField;
            }
            set {
                this.expiresField = value;
                this.RaisePropertyChanged("Expires");
            }
        }
        
        /// <remarks/>
        public byte UsageCount {
            get {
                return this.usageCountField;
            }
            set {
                this.usageCountField = value;
                this.RaisePropertyChanged("UsageCount");
            }
        }
        
        /// <remarks/>
        public System.DateTime LocationChanged {
            get {
                return this.locationChangedField;
            }
            set {
                this.locationChangedField = value;
                this.RaisePropertyChanged("LocationChanged");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileRootGroupGroupGroupEntryEntryString : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private KeePassFileRootGroupGroupGroupEntryEntryStringValue valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        public KeePassFileRootGroupGroupGroupEntryEntryStringValue Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileRootGroupGroupGroupEntryEntryStringValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string protectedField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Protected {
            get {
                return this.protectedField;
            }
            set {
                this.protectedField = value;
                this.RaisePropertyChanged("Protected");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileRootGroupGroupGroupEntryEntryAutoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string enabledField;
        
        private byte dataTransferObfuscationField;
        
        /// <remarks/>
        public string Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
                this.RaisePropertyChanged("Enabled");
            }
        }
        
        /// <remarks/>
        public byte DataTransferObfuscation {
            get {
                return this.dataTransferObfuscationField;
            }
            set {
                this.dataTransferObfuscationField = value;
                this.RaisePropertyChanged("DataTransferObfuscation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class KeePassFileRootDeletedObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uUIDField;
        
        private System.DateTime deletionTimeField;
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        public System.DateTime DeletionTime {
            get {
                return this.deletionTimeField;
            }
            set {
                this.deletionTimeField = value;
                this.RaisePropertyChanged("DeletionTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
