using NativeHelpers;
using PassKeep.Lib.Contracts.KeePass;
using SariphLib.Infrastructure;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices.WindowsRuntime;
using System.Threading;
using System.Threading.Tasks;
using Windows.Security.Cryptography.Core;
using Windows.Storage.Streams;

namespace PassKeep.Lib.KeePass.SecurityTokens
{
    /// <summary>
    /// Helper class for dealing with key transformation.
    /// </summary>
    public static class KeyHelper
    {
        /// <summary>
        /// The KeePass raw k is 32 bytes generated by the SHA-256 hash of the
        /// concatenation of all user security data.
        /// </summary>
        /// <param name="tokens">The security tokens being used to generate the raw key.</param>
        /// <returns>A 32 byte buffer to use as an encryption k</returns>
        public static async Task<IBuffer> GetRawKey(IEnumerable<ISecurityToken> tokens)
        {
            Dbg.Assert(tokens != null);
            if (tokens == null)
            {
                throw new ArgumentNullException(nameof(tokens));
            }

            var sha256 = HashAlgorithmProvider.OpenAlgorithm(HashAlgorithmNames.Sha256);
            var hash = sha256.CreateHash();

            foreach (ISecurityToken token in tokens)
            {
                hash.Append(await token.GetBufferAsync());
            }

            IBuffer rawKey = hash.GetValueAndReset();
            return rawKey;
        }

        /// <summary>
        /// Computes how many key transformation rounds can occur in one second.
        /// </summary>
        /// <returns>A task representing the computed value.</returns>
        public static Task<ulong> ComputeOneSecondDelay()
        {
            CancellationTokenSource cts = new CancellationTokenSource(TimeSpan.FromSeconds(1));
            return ComputeTransformationRounds(cts.Token);
        }

        /// <summary>
        /// Computes how many key transformation rounds can be completed before cancellation.
        /// </summary>
        /// <param name="ct">Indicates computation is finished.</param>
        /// <returns>A task representing the computated value.</returns>
        private static Task<ulong> ComputeTransformationRounds(CancellationToken ct)
        {
            return Task.Run(() =>
            {
                IBuffer keyBuffer = WindowsRuntimeBuffer.Create(new byte[32], 0, 32, 32);
                IBuffer dataBuffer = WindowsRuntimeBuffer.Create(new byte[32], 0, 32, 32);

                ConditionChecker checkForCancel = () => ct.IsCancellationRequested;
                return KeePassHelper.TransformUntilCancelled(keyBuffer, dataBuffer, checkForCancel);
            });
        }
    }
}
